# Generated by Django 5.2.6 on 2025-12-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountuser",
            name="admin_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No Admin Role"),
                    ("union_president", "Union President"),
                    ("union_vice_president", "Union Vice President"),
                    ("media_admin", "Media Admin"),
                    ("operations_admin", "Operations Admin"),
                    ("committee_lead", "Committee Lead"),
                    ("dev_admin", "Development Admin"),
                ],
                default="none",
                max_length=32,
            ),
        ),
    ]
